# Generated by Django 4.1.6 on 2023-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ages",
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="cost",
            field=models.CharField(default=5000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
