# Generated by Django 4.1.6 on 2023-03-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_course_ages_course_cost_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="oral_assessment",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="presentation",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="quiz_questions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="video_lesson",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="written_assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="authentication.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="authentication.quizquestion",
                    ),
                ),
            ],
        ),
    ]
